### ISSUE TITLE
vue and vue-server-renderer versions incompatible

### ISSUE THREAD

**Issue by justincervantes** [creativetimofficial/ct-nuxt-argon-dashboard-pro-laravel#4] opened 2021-09-10 15:42 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed
- [ X ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

npm versions should be the same for vue and vue-server-renderer

# Current Behavior
npm run build refuses to complete, throwing the below error. I can only resolve it by manually changing my vue versionto 2.6.14 from 2.6.12.

✖ Nuxt Fatal Error                                                                       
   │   Error:                                                                                   
   │                                                                                            
   │   Vue packages version mismatch:                                                           
   │                                                                                            
   │   - vue@2.6.12                                                                             
   │   - vue-server-renderer@2.6.14   

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. Download package
2. cd into file
3. npm i
4. npm run dev

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Laptop
* Operating System: Windows 10 Home
* Browser and Version: Chrome 93.0.4577.63
* Node v14.17.3
* The program runs if I manually change vue from "vue": "2.6.12" to "vue": "2.6.14"
* Tried resolving this by deleting package-lock.json and node_modules, re-running npm i, npm audit fix, and npm update. I tried all solutions from: https://github.com/nuxt/nuxt.js/issues/6823

## Failure Logs
> nuxt-argon-dashboard-pro@1.3.0 dev C:\Users\Justin Cervantes\Downloads\nuxt-argon-dashboard-pro-v1.3.0
> nuxt

ENV development                                                                                                                                                                                09:38:56

 FATAL                                                                                                                                                                                         09:38:56  

Vue packages version mismatch:

- vue@2.6.12
- vue-server-renderer@2.6.14

This may cause things to work incorrectly. Make sure to use the same version for both.

  Vue packages version mismatch:

  - vue@2.6.12
  - vue-server-renderer@2.6.14

  This may cause things to work incorrectly. Make sure to use the same version for both.

  at Object.<anonymous> (node_modules\vue-server-renderer\index.js:8:9)
  at Module.o._compile (node_modules\jiti\dist\v8cache.js:2:2778)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  at Module.load (internal/modules/cjs/loader.js:950:32)
  at Function.Module._load (internal/modules/cjs/loader.js:790:14)
  at Module.require (internal/modules/cjs/loader.js:974:19)
  at n (node_modules\jiti\dist\v8cache.js:2:2472)
  at Object.<anonymous> (node_modules\@nuxt\vue-renderer\dist\vue-renderer.js:19:27)
  at Module.o._compile (node_modules\jiti\dist\v8cache.js:2:2778)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

✖ Nuxt Fatal Error                                                                       
   │   Error:                                                                                   
   │                                                                                            
   │   Vue packages version mismatch:                                                           
   │                                                                                            
   │   - vue@2.6.12                                                                             
   │   - vue-server-renderer@2.6.14   

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-argon-dashboard-pro@1.3.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt-argon-dashboard-pro@1.3.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\npm-cache\_logs\2021-09-10T15_38_56_800Z-debug.log

**Comment by teamupdivision** [comment] 2021-09-20 10:40
Hi @justincervantes,

Thanks for reporting this issue and for using Creative Tim products.

We did more types of tests, but unfortunately, we were not able to reproduce the error. However, the solving steps should be:

rm package-lock.json
rm -rf node_modules
npm update
npm install

If this doesn’t work, could you try to install with another npm version? This may be another way to solve this.
 
Please let us know. 

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment] 2021-12-16 14:06
Hi @justincervantes,
 
Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Closed by teamupdivision** 2021-12-16 14:06 UTC
